version: '3.8'

services:
  db:
    image: postgres:14
    container_name: technicalChallenge-db
    restart: always
    environment:
      POSTGRES_DB: technicalChallenge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: technicalChallenge-api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
