spring:
  datasource:
    url: jdbc:postgresql://db:5432/technicalChallenge
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: INFO
    com.example.percentageApi.technicalChallenge: DEBUG
